### ISSUE TITLE
Please, add your repeat sequence.

### ISSUE THREAD

**Issue by ntinamu001** [Alan-Collins/CRISPR_comparison_toolkit#1]
We discovered that the CRISPR subtype repeats from the P.inopinatus are not included in your default database.

Here, CRISPR repeat sequence information (direction is confirmed).

GTTTTAGAAGAGTGTCGAATCAATATAGTTAAGATC

Also, some of the repeat mutant sequence (Marked with bold)

GTTTTAGAAGAGTGTCGAATCAATATAGTTAA**TGAG**

GTTTTAGAAGAGTGTCGAATCAATATAGTTAA**A**ATC

**ACC**TT**CA**AAGAGTGTCGAATCAATATAGTTAAGATC

GTT**C**TAGAAGAGTGTCGAATCAATATAGTTAAGATC

I also attached a figure to illustrate the sequence difference above.
![image](https://user-images.githubusercontent.com/8298573/200009789-d70a294c-d107-4fb6-98a6-d77d8f32bf36.png)

If you add my subtypes to the database it will be helpful for the analysis.

Best regards,
Wooje

**Comment by Alan-Collins** [comment]
Thank you for contributing this repeat sequence! Added in [77b1e84](https://github.com/Alan-Collins/CRISPR_comparison_toolkit/commit/77b1e84e30d4d6bb2e880d04b7f9aa07502adb77)

**Comment by ntinamu001** [comment]
> Thank you for contributing this repeat sequence! Added in [77b1e84](https://github.com/Alan-Collins/CRISPR_comparison_toolkit/commit/77b1e84e30d4d6bb2e880d04b7f9aa07502adb77)

Thank you for the update.
Wooje
